title: "Con-crastinate"
description: "Record everything"
url: "https://joeholee.github.io"
baseurl: "" # github.io 블로그는 보통 빈 값

remote_theme: "mmistakes/minimal-mistakes"

# 기본 설정
author:
  name   : "Joeho"
  avatar : "/assets/images/profile.png"
  bio    : "Backend & Data Engineering"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/joeholee"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/
